# Generated by Django 5.2.5 on 2025-08-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Κατηγορία',
                'verbose_name_plural': 'Κατηγορίες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Τίτλος')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=240, verbose_name='Περίληψη')),
                ('content', models.TextField(verbose_name='Κείμενο')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Εξώφυλλο')),
                ('published', models.BooleanField(default=True, verbose_name='Δημοσιευμένο')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='posts.category')),
            ],
            options={
                'verbose_name': 'Ανάρτηση',
                'verbose_name_plural': 'Αναρτήσεις',
                'ordering': ['-created'],
            },
        ),
    ]
